- name: delete app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    directory: absent 

- name: create directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory


- name: download and uzip the code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ components }}-v2.zip
    dest: {{ app_location }}
    remote_src: yes